// Code generated by "stringer -type=Permissions"; DO NOT EDIT

package auth

import "fmt"

const _Permissions_name = "PermsMemberCreatePermsMemberReadPermsMemberUpdatePermsMemberDelete"

var _Permissions_index = [...]uint8{0, 17, 32, 49, 66}

func (i Permissions) String() string {
	if i < 0 || i >= Permissions(len(_Permissions_index)-1) {
		return fmt.Sprintf("Permissions(%d)", i)
	}
	return _Permissions_name[_Permissions_index[i]:_Permissions_index[i+1]]
}
